Parameters:
  BucketNameParameter:
    Type: String
    Description: "The name of the S3 bucket"

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketNameParameter

Outputs:
  BucketARN:
    Description: "The ARN of the S3 bucket"
    Value: !GetAtt MyS3Bucket.Arn
