Mappings:
  RegionMap:
    eu-central-1:
      AMI: "ami-071878317c449ae48"
    us-west-1:
      AMI: "ami-0bdb828fd58c52235"

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: "The EC2 instance type"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", AMI ]
